### ISSUE TITLE
Automate Publisher html and css generation with scripts.

### ISSUE THREAD

**Issue by CuddleBear92** [CuddleBear92/Ubooquity-Themes#5]
Automate Publisher html and css generation with scripts.

Publisher list: https://www.comixology.com/browse-publisher
Publisher Example: https://www.comixology.com/DC/comics-publisher/1-0
### Generate Publisher HTML
Example Output
- [x] Copy imprint buttons (cross imprint inside the publisher (DC Comics VS Vertigo for example.)
- [x] saved into /Comics/publishernamehere/folder-info.html

Example:
```
<link rel="stylesheet" type="text/css" href="[[FOLDER]]/folder.css">
<script src="../../theme/jquery-3.1.1.min.js"></script>
<script src="../../theme/theme.js"></script>
<div id="userinfo2"></div>
<div align="center"><img src="[[FOLDER]]/header.jpg" width="100%"></div>
<div class="imprintNav">
    <ul>
        <li><a class="active" href="/ubooquity/comics/7/">DC Comics</a></li>
        <li><a href="/ubooquity/comics/49192/">Vertigo</a></li>
	<li><a href="/ubooquity/comics/1333307/">MAD</a></li>
	<li><a href="/ubooquity/comics/7/">Minx</a></li>
	<li><a href="/ubooquity/comics/7/">Paradox Press</a></li>
	<li><a href="/ubooquity/comics/7/">Wildstorm</a></li>
    </ul>
</div>
```
Only the Imprint changes here, if no imprint then no <div class="imprintNav"> should be written at all to keep it clean. (imprint ID's can be ignored as they are unique to each Ubooquity Server)

Example of Imprint nav bar look: 
![image](https://user-images.githubusercontent.com/8496821/72553076-68a43d80-3898-11ea-816e-a8dce4c61655.png)

### Generate Publisher CSS
- [x] Pull background color and text/link colors and write to CSS file
- [x] saved into /Comics/publishernamehere/folder.css

Example: https://www.comixology.com/Aspen-Comics/comics-publisher/6-0
```
#group{
	background-color: #007cd1 !important;
	color: white !important;
	padding-top: 0;
}

.label{
    color: white !important;
}
```
Adding ` !important` at the end here will make sure it loads over any other rule.

![image](https://user-images.githubusercontent.com/8496821/72553351-e9fbd000-3898-11ea-95bc-9f3cf3dce0f0.png)

### Grab Images
- [x] Grab Publisher Image 
- [x] Save publisher thumbnail into /Comics/publishernamehere/folder.jpg and theme/publisher/publishername.jpg to be referenced in series from within the theme.)
- [x] Grab Publisher Banner
- [x] Save publisher Banner into /Comics/publishernamehere/header.jpg and 

All in all, the most important parts are the images and the folders they are placed in 

Tacking on Series scraping:
- [x] Download Series thumbnail (sqare)
- [x] Save thumbnail to /comics/publishernamehere/seriesnamehere (Year)/folder.jpg
- [x] Pull Description, Series name, Year and Publisher and fill `/comics/publishernamehere/seriesnamehere (Year)/series.json` like bellow.

```
{ "metadata": [ { "description": "<p><em>DESCRIPTION TEXT HERE </em></p>", "name": "Adventure Time Comics", "year": "2016", "publisher": "Boom! Studios", "type": "comicSeries" } ] }
```

**Comment by cryzed** [comment]
https://gist.github.com/cryzed/3cd9d0f914a3581ef8262301e204fbd7

You will need `requests`, `beautifulsoup4` and `html5lib` installable via pip.
